spring:
#  logging:
#    level:
#      org.springframework.mail: INFO
#      org.springframework.mail.javamail: INFO
#      jakarta.mail: INFO

  application:
    name: investment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/investment_tracker
    username: investment_user
    password: securepassword
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jwt:
    secret: ${JWT_SECRET}

